version: "3.7"
services: 
    db: 
        build: "./src/database"
        container_name: mongodb-99hero
        environment: 
            MONGO_INITDB_ROOT_USERNAME: 'mongoadmin'
            MONGO_INITDB_ROOT_PASSWORD: 'secret'
            MONGO_INITDB_DATABASE: 'noderest'
        restart: always
        volumes:
            #Cria usuario com senha no banco de dados
            - ./src/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        ports:
            - "9002:27017"